UpdateInterval: 100
Tags:
  Groups:
    Member:
      Prefix: '&7'
      Suffix: '&f:)'
      Priority: 0
    Mod:
      Prefix: '&a[Mod]'
      Suffix: '&4<3'
      Priority: 2
  Players:
    Giverzin:
      Prefix: '&a '
      Suffix: '&c []'
      Priority: 5